# Generated by Django 4.1.4 on 2023-03-10 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='content',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='contentcategory',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='contentcategory',
            name='update_time',
        ),
    ]
