# Generated by Django 4.1.4 on 2023-04-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sku",
            name="default_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="默认图片"
            ),
        ),
    ]
