# Generated by Django 4.1.4 on 2023-12-29 06:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GoodsVisitCount",
        ),
    ]
