# Generated by Django 4.1.4 on 2023-02-22 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_user_default_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-update_time'], 'verbose_name': '用户地址', 'verbose_name_plural': '用户地址'},
        ),
        migrations.AddField(
            model_name='address',
            name='receiver',
            field=models.CharField(default='', max_length=20, verbose_name='收货人'),
        ),
        migrations.AddField(
            model_name='address',
            name='title',
            field=models.CharField(default='', max_length=20, verbose_name='地址名称'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterModelTable(
            name='address',
            table='tb_address',
        ),
    ]
