# Generated by Django 4.1.4 on 2023-02-22 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('users', '0004_alter_address_options_address_receiver_address_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='province_addresses', to='areas.area', verbose_name='省'),
        ),
    ]
