# Generated by Django 4.1.4 on 2023-02-22 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('users', '0005_address_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='city_addresses', to='areas.area', verbose_name='市'),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='district_addresses', to='areas.area', verbose_name='区'),
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='电子邮箱'),
        ),
        migrations.AddField(
            model_name='address',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(max_length=11, null=True, verbose_name='手机'),
        ),
        migrations.AddField(
            model_name='address',
            name='place',
            field=models.CharField(max_length=50, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='address',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='固定电话'),
        ),
    ]
