# Generated by Django 4.1.4 on 2023-12-29 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goods", "0001_initial"),
        ("users", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderinfo",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.address",
                verbose_name="收货地址",
            ),
        ),
        migrations.AddField(
            model_name="orderinfo",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="下单用户",
            ),
        ),
        migrations.AddField(
            model_name="ordergoods",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skus",
                to="orders.orderinfo",
                verbose_name="订单",
            ),
        ),
        migrations.AddField(
            model_name="ordergoods",
            name="sku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="goods.sku",
                verbose_name="订单商品",
            ),
        ),
    ]
