# Generated by Django 4.1.4 on 2023-10-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordergoods",
            name="score",
            field=models.SmallIntegerField(
                choices=[
                    (0, "0分"),
                    (1, "20分"),
                    (2, "40分"),
                    (3, "60分"),
                    (4, "80分"),
                    (5, "100分"),
                ],
                default=3,
                verbose_name="满意度评分",
            ),
        ),
    ]
